from typing import Dict


def generate_markdown_report(result: Dict) -> str:
    metadata = result["report_metadata"]
    insights = result["validated_insights"]

    md = f"""
            # Market Intelligence Report

            **Query:** {metadata['query']}  
            **Generated:** {metadata['timestamp']}  
            **Confidence Score:** {metadata['confidence_score']:.2f}  
            **Total Sources:** {metadata['total_sources']}

            ---

            ## 🏢 Identified Competitors

            {', '.join(insights.get('competitors', []))}

            ---

            ## 📝 Content Themes

            """

    for theme in insights.get("content_themes", []):
        md += f"### {theme.get('theme','')}\n"
        md += f"- **Frequency:** {theme.get('frequency','N/A')}\n"
        md += f"- **Sentiment:** {theme.get('sentiment','N/A')}\n\n"

    md += """
        ---

        ## 💡 Content Recommendations

        """

    for rec in insights.get("content_recommendations", []):
        md += f"### {rec.get('topic','Untitled')}\n"
        md += f"- **Priority:** {rec.get('priority','-')}\n"
        md += f"- **Opportunity Score:** {rec.get('opportunity_score','N/A')}\n"
        md += f"- **Search Volume:** {rec.get('search_volume_monthly','N/A')}\n\n"

    md += """
        ---

        ## 🎯 Strategic Recommendations

        """

    for move in insights.get("strategic_recommendations", []):
        md += f"- {move}\n"

    if result.get("quality_flags"):
        md += "\n---\n\n## ⚠️ Quality Flags\n\n"
        for flag in result["quality_flags"]:
            md += f"- **{flag['type'].upper()}:** {flag['message']}\n"

    md += """
---

*Generated by Market Horizon AI*
"""

    return md


